#pragma once

// Shared by the control-core tests: the test robot's URDF (generated by CMake from its xacro),
// its robot.yaml, and a simulated plant (Pinocchio forward dynamics, semi-implicit Euler).

#include <fstream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

#include <Eigen/Core>
#include <yaml-cpp/yaml.h>

#include "arm_sandbox_controllers/robot_dynamics.hpp"

namespace arm_sandbox_controllers::test
{

struct RobotConfig
{
  std::vector<std::string> arm_joints;
  std::string base_frame;
  std::string ee_frame;
  Eigen::VectorXd home;
};

inline std::string robot_urdf()
{
  std::ifstream file(TEST_URDF_PATH);
  if (!file) {
    throw std::runtime_error("cannot read " TEST_URDF_PATH);
  }
  std::stringstream contents;
  contents << file.rdbuf();
  return contents.str();
}

inline RobotConfig robot_config()
{
  const YAML::Node yaml = YAML::LoadFile(TEST_ROBOT_CONFIG_PATH);
  RobotConfig config;
  config.arm_joints = yaml["arm_joints"].as<std::vector<std::string>>();
  config.base_frame = yaml["base_frame"].as<std::string>();
  config.ee_frame = yaml["ee_frame"].as<std::string>();
  const auto home = yaml["home"].as<std::vector<double>>();
  config.home = Eigen::Map<const Eigen::VectorXd>(home.data(), static_cast<Eigen::Index>(home.size()));
  return config;
}

/// The simulated arm: its own RobotDynamics (gravity always acts on it), stepped with
/// semi-implicit Euler at the controller rate.
class Plant
{
public:
  Plant(const std::string & urdf, const std::vector<std::string> & joints, const Eigen::VectorXd & armature, const Eigen::VectorXd & q0)
  : dynamics_(urdf, joints, armature), q(q0), qd(Eigen::VectorXd::Zero(q0.size()))
  {
  }

  void step(const Eigen::VectorXd & tau, double dt)
  {
    qd += dynamics_.forward_dynamics(q, qd, tau) * dt;
    q += qd * dt;
  }

private:
  RobotDynamics dynamics_;

public:
  Eigen::VectorXd q;
  Eigen::VectorXd qd;
};

}  // namespace arm_sandbox_controllers::test
