#pragma once

// Shared by the kinematics tests: the test robot's URDF (generated by CMake from its xacro) and
// its robot.yaml, plus a seeded generator of random configurations inside the joint limits.

#include <fstream>
#include <random>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

#include <Eigen/Core>
#include <yaml-cpp/yaml.h>

#include "arm_sandbox_kinematics/kinematic_chain.hpp"

namespace arm_sandbox_kinematics::test
{

struct RobotConfig
{
  std::vector<std::string> arm_joints;
  std::string base_frame;
  std::string ee_frame;
  Eigen::VectorXd home;
};

inline std::string read_file(const std::string & path)
{
  std::ifstream file(path);
  if (!file) {
    throw std::runtime_error("cannot read " + path);
  }
  std::stringstream contents;
  contents << file.rdbuf();
  return contents.str();
}

inline std::string robot_urdf() { return read_file(TEST_URDF_PATH); }

inline RobotConfig robot_config()
{
  const YAML::Node yaml = YAML::LoadFile(TEST_ROBOT_CONFIG_PATH);
  RobotConfig config;
  config.arm_joints = yaml["arm_joints"].as<std::vector<std::string>>();
  config.base_frame = yaml["base_frame"].as<std::string>();
  config.ee_frame = yaml["ee_frame"].as<std::string>();
  const auto home = yaml["home"].as<std::vector<double>>();
  config.home = Eigen::Map<const Eigen::VectorXd>(home.data(), static_cast<Eigen::Index>(home.size()));
  return config;
}

/// Uniformly random configurations inside the chain's joint limits, reproducible per seed.
class RandomConfigurations
{
public:
  RandomConfigurations(const KinematicChain & chain, unsigned seed) : chain_(chain), generator_(seed) {}

  Eigen::VectorXd next()
  {
    Eigen::VectorXd q(static_cast<Eigen::Index>(chain_.num_joints()));
    for (Eigen::Index i = 0; i < q.size(); ++i) {
      std::uniform_real_distribution<double> range(chain_.lower_limits()[i], chain_.upper_limits()[i]);
      q[i] = range(generator_);
    }
    return q;
  }

  std::mt19937 & generator() { return generator_; }

private:
  const KinematicChain & chain_;
  std::mt19937 generator_;
};

}  // namespace arm_sandbox_kinematics::test
