#!/usr/bin/env bash
# Write docker/docker-compose.local.yml, the per-PC compose override that enables the NVIDIA GPU
# when this host has one. Runs on the host before the container starts: the Makefile and
# .devcontainer/devcontainer.json (initializeCommand) both call it, so one config works on GPU
# PCs and CPU-only laptops. The generated file is gitignored.
#
# Usage:  scripts/select_gpu.sh          auto-detect (nvidia runtime in `docker info`)
#         GPU=1 scripts/select_gpu.sh    force GPU
#         GPU=0 scripts/select_gpu.sh    force CPU-only
# A permanent per-PC choice can go in docker/.env as `GPU=0` or `GPU=1` (the env var wins).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
readonly REPO_ROOT
readonly OVERRIDE_FILE="${REPO_ROOT}/docker/docker-compose.local.yml"
readonly ENV_FILE="${REPO_ROOT}/docker/.env"

gpu_mode_from_env_file() {
    if [ -f "${ENV_FILE}" ]; then
        sed -n 's/^GPU=//p' "${ENV_FILE}" | tail -n 1
    fi
}

GPU_MODE="${GPU:-$(gpu_mode_from_env_file)}"
readonly GPU_MODE="${GPU_MODE:-auto}"

has_nvidia_runtime() {
    docker info --format '{{json .Runtimes}}' 2>/dev/null | grep -q nvidia
}

gpu_enabled() {
    case "${GPU_MODE}" in
        1) return 0 ;;
        0) return 1 ;;
        auto) has_nvidia_runtime ;;
        *)
            echo "Error: GPU must be auto, 1 or 0 (got '${GPU_MODE}')." >&2
            exit 1
            ;;
    esac
}

write_gpu_override() {
    cat > "${OVERRIDE_FILE}" <<'EOF'
# Generated by scripts/select_gpu.sh (GPU enabled). Do not edit, do not commit.
services:
  sandbox:
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all # graphics (EGL/GL) too, not just CUDA
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
EOF
}

write_cpu_override() {
    cat > "${OVERRIDE_FILE}" <<'EOF'
# Generated by scripts/select_gpu.sh (CPU-only: MuJoCo renders through Mesa llvmpipe).
# Do not edit, do not commit.
services:
  sandbox: {}
EOF
}

main() {
    if gpu_enabled; then
        write_gpu_override
        echo "select_gpu: NVIDIA GPU enabled (GPU=${GPU_MODE}) -> ${OVERRIDE_FILE}"
    else
        write_cpu_override
        echo "select_gpu: CPU-only (GPU=${GPU_MODE}) -> ${OVERRIDE_FILE}"
    fi
}

main "$@"
